### ISSUE TITLE
What is the effect of this?

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#12]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L161

It looks like initialization/zeroing, but it is always overwritten later.

**Comment by NucciTheBoss** [comment]
I use this to purge the token if there is a prior existing one. This is due to the fact that the token persists in the relation's data bag after the first run of the `start` action. I had issues with the program exiting early in my original approach, but it might not be an issue.

Will need to test if it is still an issue.

**Comment by j4m-can** [comment]
ok. But just noting that you overwrite/set afterward anyways so the purge doesn't actually do anything useful.

**Comment by NucciTheBoss** [comment]
Fixed in the latest commit.
