### ISSUE TITLE
Why round()?

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#13]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L168

**Comment by NucciTheBoss** [comment]
The reason why I used `round` was due to how the `time.time()` method outputs the current time:

```
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> time.time()
1662038514.3820436
```

I used `round()` to make the output nicer in the ActiveStatus messages as well as reduce arithmetic issues such as the ole floating point precision issue where `2.1 + 2.2 = 2.3000000000000000000001`. I mostly did this so that I would not need to also import the `Numbers` class from the standard library.

**Comment by NucciTheBoss** [comment]
Fixed in the latest update.
