### ISSUE TITLE
Why use a dict instead of individual items?

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#14]
https://github.com/NucciTheBoss/charming-exercises/blob/22b9a8930a85cbb7b5e072abd262e67451caf66b/hot-potato/src/charm.py#L105-L109

Why not use ```self._stored.passes``` and ```self._stored.delay```? Is there are benefit to one way or the other?

**Comment by NucciTheBoss** [comment]
I like using dictionaries because they are mutable, and I like the interface for updating key-value pairings. Helps prevent me from falling into the pit-trap of accidentally trying to modify strings in place like `var.strip('\n')` instead of reassigning the value like `var = var.strip('\n')`. Once again, this is mostly a stylistic choice.
