### ISSUE TITLE
When to set unit status

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#2]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L111

Is this the correct place to set the ```unit.status```? What happens when this call is in the init()?

**Comment by NucciTheBoss** [comment]
I set the unit to active status in the `__init__(self)` because otherwise (at least on my local LXD cluster) it will set the unit's status to `unknown` when the charm is deployed which I do not find favorable.

Adding `self.unit.status = ActiveStatus()` in __init__ let's me know that everything is installed and ready.

**Comment by j4m-can** [comment]
init is not the right place because that affects the operator every time it is run, no matter what the operator is being run for, and it does this without knowing anything, it doesn't even have the event. So, if the status was already set, this will reset it to Active which may be completely wrong.

The proper place to set this is in an event handler (or possibly, but less likely, an action). So, if you want things to come up nicely, put something in the install handler, start handler, config_changed handler, etc.

**Comment by NucciTheBoss** [comment]
Fixed in the latest commit.
