### ISSUE TITLE
Why update status like this?

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#3]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L45-L58

When does ```unit.status``` actually get updated?

**Comment by NucciTheBoss** [comment]
Unit status is updated after the token has been received and deserialized. The unit displays what it has received, updates the token, sleeps for the set delay, and then clears the message. This way only one unit is showing the token's status at a time.

**Comment by j4m-can** [comment]
Because there is a delay between 1) clearing the status and 2) the "next" unit getting the event and responding to it, there will be an unknown amount of time when no units show a message. How would you deal with this?

**Comment by NucciTheBoss** [comment]
Either write in the docstring for the method `"""trust me bro, it will get to the next unit eventually"""` or find some way to update the status from another unit. 

I originally did it this way due to not being able to update statuses from another unit. It caused issues in `juju status` because it would show stale messages. This made it harder to track the progress of the message. Therefore, I decided the best course of action was to clear the current unit's status before passing the token off to the next unit.

**Comment by j4m-can** [comment]
Well, the docstring approach is not going to win kudos.

For this exercise it is not critical, but at some point this kind of situation will require something more which actually does report something useful. Even for this exercise, the token has not been passed until the transaction completes. Namely, the receiver "accepts" it.

I was going to let this go. But since you are putting status info, come up with a way to make this useful. There are a number of options.

**Comment by NucciTheBoss** [comment]
Closing this issue as it is not necessary to address issues in this repository.
