### ISSUE TITLE
Good way to handle data interchange!

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/hot-potato-charm#4]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L69-L74

Although there is no validation, using ```json``` to serialize is good when it suffices. Avoids constant casting in and out!

What are the pros of putting all the information in one object?

What are the cons of putting all the information in one object?

**Comment by NucciTheBoss** [comment]
### Pros
* I do not need to check if certain keys are available in the relation data bucket. I only need to check if a specific key->value pairing is present.
* If I wanted to, I could write a more advanced decoder/encoder for deconstructing an object on one end and reconstructing it on the other end. That way, I could exchange more advanced data such as a dataclass rather than just a dictionary.
* Keeps metadata in one place. I do not need to make constant calls out to the data bucket.

### Cons
* I can only use a single Decoder/Encoder for the object. Therefore, I could not do any advanced object nesting unless I knew it was there.
* The more complex the object, the more complex the Decoder/Encoder. I can get away with it here since the data types we are working with are rather simple, but if I were to do a more advanced object, I would most likely hate myself trying to debug the Decoder/Encoder

**Comment by j4m-can** [comment]
Nice.

I would also add:
* once the data in the bucket is available, it is actually cached. So, even though the data is stored on the controller, each call to the data bucket from the operator is local (from the cache).
* one needs to be careful with an extensible object in the data bucket, depending on the interface.
* if there is data in the data bucket, it should have been initialized so that searching for some expected key, value will not cause an error and will not need a stream of ```if key in dict```.

**Comment by NucciTheBoss** [comment]
Insightful!
